---
# PersistentVolumeClaim cho HDFS NameNode
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdfs-namenode-pvc
  namespace: bigdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard-rwo  # GKE standard persistent disk
---
# PersistentVolumeClaim cho HDFS DataNode
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdfs-datanode-pvc
  namespace: bigdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard-rwo
---
# PersistentVolumeClaim cho Elasticsearch
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: bigdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard-rwo
---
# PersistentVolumeClaim cho Zookeeper
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-pvc
  namespace: bigdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo
---
# PersistentVolumeClaim cho Kafka
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
  namespace: bigdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard-rwo
